### ISSUE TITLE
FR: Add a proper date picker

### ISSUE THREAD

**Issue by isle9** [argenos/nldates-obsidian#105]
Something similar to this:
![image](https://user-images.githubusercontent.com/74906541/177001799-97d4c74e-a594-48d4-9060-b8f936d2a48b.png)

Graphical buttons for quickly inserting today, tomorrow, next week, next month etc. would also be welcome.
The date picker could just be one of those options.
And these options don't even need to be hard-coded. It would be nice if the options were able to be picked in the settings.

Examples for graphical buttons:
![image](https://user-images.githubusercontent.com/74906541/177001881-dbe36431-9d5a-4907-b5b2-c39fb63b855a.png)
![image](https://user-images.githubusercontent.com/74906541/177001893-84c39d0c-e9a6-4a90-94a3-6699ed057d05.png)

**Comment by argenos** [comment]
I'm afraid that is a bit out of scope since the focus of the plugin is about **natural language**
