### ISSUE TITLE
Localized names of week days -> disconnected with configuration

### ISSUE THREAD

**Issue by dariuszkowalski-com** [argenos/nldates-obsidian#11]
Before version 0.9.22 Plugins like Calendar or Natural Languages Dates use always
English version of days: Monday, Friday.

I have set the language of Obsidian to English. My Windows 10 has Polish Localisation.

Begining from Obsidian 0.9.22 I have got Polish names o week days (Poniedziałek, Piątek)

Now the Calendar plugin does not show me my previous notes (which have got an English name) and all new ones are created using Polish language localization.

For me, the language in Obsidian should be determined by the option set in the configuration.

**Comment by argenos** [comment]
Can you share what you have as your daily notes/nldates format?

**Comment by argenos** [comment]
Where are you actually setting the locale for your daily notes? I don't see this available anywhere.

**Comment by argenos** [comment]
I'm going to close this one to keep the discussion in a single place: https://github.com/liamcain/obsidian-calendar-plugin/issues/68

**Comment by empik-foto-it** [comment]
it was a bug in Calendar plugin.
https://github.com/liamcain/obsidian-calendar-plugin/issues/68
