### ISSUE TITLE
0.6.1. not loading on Mac with Obsidian v0.12.3

### ISSUE THREAD

**Issue by michaelaye** [argenos/nldates-obsidian#114]
Not sure what else I can say, is there some log I can store from the loading process?

The symptom is, whenever I try to activate the plugin by clicking on the switch, it automatically goes off again and a notification appears saying "Failed to load plugin".

**Comment by cabbage** [comment]
Hade the same behaviour. My issue was that the `main.js` was missing (probably a sync issue on my side I guess).

You can check the console by opening up the Developer Tools (Menu: View > Toggle Developer Tools; Hotkey: `⌘`+`⌥`+`i`) And go to the "Console" tab. Watch the console while you try to enable the plugin and you should probably see an error message.

**Comment by argenos** [comment]
0.6.1 requires Obsidian v0.13.0 or above
