### ISSUE TITLE
YYYY-MM-DD_ddd not working

### ISSUE THREAD

**Issue by mdelobelle** [argenos/nldates-obsidian#117]
When parsed, a date-string with this format is converted into another date. See this issue opened on metadatamenu repo https://github.com/mdelobelle/metadatamenu/issues/147

**Comment by mdelobelle** [comment]
And by the way, thanks a lot for this great plugin! I use it dozens times a day, it is super robust 👍🏻

**Comment by argenos** [comment]
Sorry, but I may be missing a lot of context even when I read the issue in metadatamenu. It sounded like a conflict between both plugins using `@` as a trigger, but I can't say if I understood right. Can you expand on what is the bug?

**Comment by mdelobelle** [comment]
Sure! 
In a clean new vault:
here are the settings for the nldates plugin
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/1233240/202870047-deb43e4e-5ef9-443c-b866-ccbb0604cdff.png">

when i type @today for example
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/1233240/202870073-e9de0d0c-1436-4465-ab96-1c1091598111.png">

Here is the result:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/1233240/202870097-3ba7e486-2035-4cf7-abb5-c3f3f8530507.png">

Everything's fine

But when I type a full date:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1233240/202870162-18239327-8bc1-4816-835a-048d449d8f81.png">

Here is the result
<img width="785" alt="image" src="https://user-images.githubusercontent.com/1233240/202870197-3208fea2-1138-43c7-be39-749dfb7f3a49.png">

This is just happening with YYYY-MM-DD_ddd format, if I change the date format to YYYY-DD-MM ddd everything is working as expected

**Comment by argenos** [comment]
I'm not sure that counts as a date in natural language, e.g. try with 2022-11-19 Sat (with the space instead of the last underscore).

**Comment by mdelobelle** [comment]
I do think so. I'll close this issue thanks.
