### ISSUE TITLE
Conflict with Various Complements plugin

### ISSUE THREAD

**Issue by SmartAI** [argenos/nldates-obsidian#128]
Autosuggest do not work when I enable auto completion in Various Complements plugin

<img width="823" alt="image" src="https://user-images.githubusercontent.com/19516876/230446947-374f4442-3285-49ba-b15a-a6eaafc8bf8e.png">

**Comment by menteValidus** [comment]
I have the same issue here.

**Comment by nugmanoff** [comment]
Hey @SmartAI @menteValidus – I had the same issue and fixed it by adding `@` to **First characters to disable suggestions** setting in Various Complements plugin's settings.

Hope it helps

<img width="776" alt="CleanShot 2023-04-21 at 13 37 17@2x" src="https://user-images.githubusercontent.com/20473743/233573294-753976e1-2d93-4d19-b21d-9f2a82432a40.png">

**Comment by SmartAI** [comment]
> Hey @SmartAI @menteValidus – I had the same issue and fixed it by adding `@` to **First characters to disable suggestions** setting in Various Complements plugin's settings.
> 
> Hope it helps
> 
> <img alt="CleanShot 2023-04-21 at 13 37 17@2x" width="776" src="https://user-images.githubusercontent.com/20473743/233573294-753976e1-2d93-4d19-b21d-9f2a82432a40.png">

Thank a lot @nugmanoff , it solved my problem
