### ISSUE TITLE
Autosuggest and table cells (insider build v1.5.4)

### ISSUE THREAD

**Issue by atyopsis** [argenos/nldates-obsidian#149]
As of the v1.5.4 insider build, autosuggest no longer works in the context of editing a cell with the live-preview table editor. As seen below, the dialog only shows up for a split second.

![Peek 2024-02-12 19-49](https://github.com/argenos/nldates-obsidian/assets/151197672/87b81da6-76f8-4854-8a57-ca0713aefa8b)

**Comment by liamcain** [comment]
This is a bug in Obsidian v1.5.4. It will be fixed in the upcoming 1.5.5
