### ISSUE TITLE
Include option to parse date/time to plain text (instead of link)

### ISSUE THREAD

**Issue by arnoan** [argenos/nldates-obsidian#15]
First off, thank you for the wonderful plugin 👍👏

I am using your Date Parsing Plugin in conjunction with the [Day Planner Plugin](https://github.com/lynchjames/obsidian-day-planner) by James Lynch to create timers for focused work on the spot. 

Example:
```
## Day Planner
- [ ] now Morning review
- [ ] in 15m Read
- [ ] in 1h BREAK
```

Selecting the natural dates/times (*now*, *in 15m*, *in 1h*) and using the shortcut or command from your plugin translates them to the desired times. So when executed for example at 7am the resulting output would be:

```
## Day Planner
- [ ] [[07:00]] Morning review
- [ ] [[07:15]] Read
- [ ] [[08:00]] BREAK
```

For this to work I set the output date format to `HH:mm`. 

This functionality is already highly useful. However the Dat Planner plugin can only parse times in plain text. So at the moment I manually remove the `[[`, `]]` from each timestamp again to obtain my **desired output**:

```
## Day Planner
- [ ] 07:00 Morning review
- [ ] 07:15 Read
- [ ] 08:00 BREAK
```

Is there a possibility for adding an option to parse dates and times without creating a link? 

Alternatively, could you maybe point me to the location in the codebase where the parsing takes place? Then I can try if I can change the replacement behaviour locally for the time being. Many thanks!

**Comment by pyjamads** [comment]
Added this in my pull-request here: https://github.com/argenos/nldates-obsidian/pull/16

**Comment by arnoan** [comment]
Thank you so much @pyjamads. By looking at the [Obsidian Sample Plugin](https://github.com/obsidianmd/obsidian-sample-plugin) for reference I managed to incorporate your changes locally in a new build and everything works as desired. 👍 

(I primarily know Python and up to this point had little exposure to JS & Node, so it took me a moment to grok the compilation step from main.ts to main.js.)
