### ISSUE TITLE
Use wanasit/chrono, the reference version of chrono-node

### ISSUE THREAD

**Issue by olivr70** [argenos/nldates-obsidian#159]
While  trying to understand why some expressions were not working as expected, I went through the chrono-node module doc on NPM, which leads to the official [wanasit/chrono](https://github.com/wanasit/chrono) repo.

I discovered that NLP was using a very old fork of the chrono module, [liamcain/chrono](https://github.com/liamcain/chrono) which was last updated in 2022 and and is 218 commits behind the reference implementation.

There are probably good reasons for this choice, but I think a switch could quickly add features to NLP.

By the way, international features of wanasit/chrono are much more advanced, adding support for more languages. This switch would also make adding international features of NLP much better.

**Comment by argenos** [comment]
That would break current functionality. Did you check what was added in the fork?
