### ISSUE TITLE
daily-notes locations should inform date link path

### ISSUE THREAD

**Issue by chadmiller-saq** [argenos/nldates-obsidian#160]
In recent Obsidian, there is a core plugin configuration for Daily Notes where you can set"New file location" to be some directory.

Daily notes will be placed underneath that directory.

If that is set, then when this plugin computes the link location for a date link, that should use the daily-note location.

**Comment by chadmiller-saq** [comment]
<img width="574" alt="Screenshot 2024-10-18 at 09 48 25" src="https://github.com/user-attachments/assets/e0012350-b8e8-4560-895d-9288e4c379dd">

**Comment by argenos** [comment]
Sorry, this is something out of scope for this plugin. Please see and support this feature request in the Obsidian app: https://forum.obsidian.md/t/creating-or-recognizing-daily-notes-inline-in-the-editor/4730
