### ISSUE TITLE
Bug - "this" and "next" modifiers applied to week days are not calculated properly

### ISSUE THREAD

**Issue by azuenko** [argenos/nldates-obsidian#164]
Hello @argenos . 
Thanks for maintaining this community plugin in your free time!

I've a little bug to report. The relative dates are not correctly calculated. Although the semantics for the "last xxx" might be interpreted differently - "xxx on the previous week" rather than "the last xxx before today", the semantics of "this xxx" and "next xxx" are clearly not correctly calculated.

I'm using Obsidian 1.7.7
Nldates v0.6.2

To reproduce:
```
✅ Today (expected 2024-11-29)      : 2024-11-29 
❌ This Monday (expected 2024-11-25): 2024-11-18
❌ This Sunday (expected 2024-12-01): 2024-11-24
❌ Next Monday (expected 2024-12-02): 2024-11-25
❌ Last Monday (expected 2024-11-25): 2024-11-11
❌ Last Sunday (expected 2024-11-24): 2024-11-17
```

![Kapture 2024-11-29 at 12 33 50](https://github.com/user-attachments/assets/4f5beae5-f820-4b50-82a0-de7ad61c5ad6)

My plugin settings:
<img width="799" alt="image" src="https://github.com/user-attachments/assets/e1d2c385-01f5-48f8-aecb-ace903779cff">

**Comment by argenos** [comment]
This is discussed in #137.
