### ISSUE TITLE
Use command without select multiple-words dates

### ISSUE THREAD

**Issue by desk7** [argenos/nldates-obsidian#20]
The plugin's description says that "for single-word dates (e.g. today, tomorrow, friday, etc.), it's possible to use the command without selecting the word first."

Could you extend this feature to include also the other multiple-words date?

**Comment by argenos** [comment]
This would be quite hard to do! The reason why you need to select multi-word dates is that the parser needs to know where in your document to find them. On a particular note, how would you identify multi-word dates? How many words should the parser try to include?

**Comment by desk7** [comment]
Let me explain. I write the date, as in the demo, then, without selecting anything, I press Ctrl+Y and the parser search for multi-word dates in the words _before the cursor position_. How many words? According to the demo, the recognized expressions are at most 3 words long (e.g. in 3 weeks, in one year etc.), so the parser should search _in the 3 words before the cursor position_.
I don't mean that the parser should search the _whole_ document.

**Comment by argenos** [comment]
That could be doable but I am not sure that commands are always at most 3 words long. It probably also needs first to check the two prior words, and if it doesn't return a valid date try with three. Since I can't really promise I'll have time to look into this in the near future, I'm willing to accept PRs for this.

**Comment by twwilliams** [comment]
What if this just looked back to the beginning of the current line (or to the end of the current line) rather than searching throughout the document? That way it wouldn't have to be specifically three words.

But that's still not a trivial kind of parsing to do.

**Comment by desk7** [comment]
I honestly thought to parse 3 words is easier than a whole line.

I am not a programmer, but I would like to make an observation. Currently the plugin does the selected text.
To get the desired behavior, the plugin should automatically select the 3 words before the cursor, then do them; if it doesn't find a date, try the last 2 words; if it still doesn't find anything, try the last word.

I'll give an example.
Suppose I write
"in 2 months" and I have the cursor after the s. I press Ctrl+Y. The plugin selects the 3 words before the cursor, recognizes the date and replaces it.

Other example
Suppose I write
"I will go to the park today" and I have the cursor after y. I press Ctrl+Y. The plugin selects the 3 words before the cursor, it doesn't recognize any date. Then try with the last 2 words, it doesn't recognize any date. Then try with the last word, it recognizes the date and replaces it.

**Comment by argenos** [comment]
Not exactly the way it was requested in this issue, but I consider the auto-suggest in v0.5.0 to fix this.
