### ISSUE TITLE
Support translating strings like ";next week;" as though I had highlighted the selection between the semi-colons and pressed a keyboard shortcut

### ISSUE THREAD

**Issue by classicrob** [argenos/nldates-obsidian#21]
Highlighting a section of text and then pressing a keyboard shortcut has a little more friction than I was hoping for! Roam toolkit allows me to instead just write ;in a week; and it treats the section of text that I have between semi-colons as though it were highlighted and transformed. This just makes it a bit easier to capture this stuff while I'm writing / without breaking my flow. I'll remind you ;in one week; 😉️

**Comment by classicrob** [comment]
![image](https://user-images.githubusercontent.com/46608303/112220381-d1e5b600-8beb-11eb-92c8-6fd116854aa6.png)

Perhaps this is helpful? It's an implementation in Keyboard Maestro using regex. Preferably this would be in the plugin so I would have access on mobile as well!

**Comment by argenos** [comment]
Not exactly the way it was requested in this issue, but I consider the auto-suggest in v0.5.0 as a fix for this. Note: This doesn't work on mobile yet (I still need some missing pieces from the CM6 API)
