### ISSUE TITLE
create subfolder to be compatible with daily note

### ISSUE THREAD

**Issue by chappy721** [argenos/nldates-obsidian#25]
your extension is really gerat, thanks a lot!
One small suggestion: when inserting a link for the current date it would be great if I could use the subfolder defined in "new file location" of daily notes plugin.

**Comment by cbeier** [comment]
@chappy721 This may help you: #37

**Comment by liamcain** [comment]
Going to close this in favor of #37 since there is a workaround described in that issue. Thinking of adding a toggle in the future to always include the daily note folder though.
