### ISSUE TITLE
Replacing by highlighting doesn't work

### ISSUE THREAD

**Issue by dag7dev** [argenos/nldates-obsidian#29]
Obsidian version: v0.11.13

This doesn't work unfortunately for me, I wrote ```today``` I highlighted just that word --> it doesn't replace as it shown in the demo

**Comment by argenos** [comment]
Are there any errors in the console?

**Comment by dag7dev** [comment]
How do I suppose to open the console?

**Comment by argenos** [comment]
Usually Cmd/Ctrl + Shift + I 

Could you also mention how you triggered the conversion? Did you set the hotkey in the settings?

**Comment by dag7dev** [comment]
No error in console then.

I didn't setup the hotkey, maybe that's why?

**Comment by argenos** [comment]
How are you invoking the conversion? Please note from the README:
> (note that hotkeys are unset by default starting on v0.4.1)

**Comment by dag7dev** [comment]
@argenos maybe I misunderstood something maybe: according to the readme and what I understood, it should recognize automatically if I, let's say, write "today", shouldn't it? (it should automatically parse it, if I highlight "today").
Am I wrong? I MUST trigger something or is it automatic?

**Comment by argenos** [comment]
No, it is not automatic! You have to trigger this through the command palette or with a hotkey. Starting on version 0.5.0 you can also use the auto-suggest feature to trigger the parsing.

**Comment by dag7dev** [comment]
@argenos Thanks for clarifying this out, now it's clear!
one last thing: any clue how to trigger auto-suggest feature for parsing?

**Comment by argenos** [comment]
The default is @, but you can change this in your settings

**Comment by dag7dev** [comment]
That's clear now. Thanks for your patience!

I would highly reccomend to write these things in the README file; it will be clearer to people to understand how things work!

**Comment by argenos** [comment]
The readme does mention it! 

> To create a date link, select the text you want to change (e.g. today), and use the NLP date command. You can use the shortcut or the command palette (Ctrl + P).

**Comment by dag7dev** [comment]
@argenos you're not forced to answer me by email; however, some people are reporting me who my email goes straight to the spam folder for unknown reason. If it's the case, I just wanted to let you know that I have sent you an email and you could find it straight in your best spam folder! :D

**Comment by argenos** [comment]
Thanks! I did get your email, I just haven't gotten around to writing a reply, sorry about that.
