### ISSUE TITLE
Add support for @wednesday etc

### ISSUE THREAD

**Issue by trashhalo** [argenos/nldates-obsidian#35]
I mentally operate in a weekly timespan. Sometimes I want to say due: @wednesday to mean due the day after tomorrow. It would be nice if I could target like such.

@monday = 05-10
@tuesday = 05-11
@wednesday = 05-12
@thursday = 05-13
@friday = 05-13

Even if today was Thursday. If I said `at @monday all-hands eng were concerned about x` I am referring to the Monday from this week.

---
I just realized I pinged all these people. Ooooops

**Comment by argenos** [comment]
@trashhalo these are parser issues, and tend to come with some ambiguity depending on the day you're referencing. For the same week (usually) you can use `@this monday`, `@this tuesday`, etc., but the day of reference and your locale might also play a role. There is definitely some room for improvement in the parser and last time I tested, I didn't find a way to make chrono parse this this edge cases consistently.

**Comment by trashhalo** [comment]
I wasnt aware of `@this Monday`. Closing issue thank you.
