### ISSUE TITLE
How to insert just time?

### ISSUE THREAD

**Issue by mgook** [argenos/nldates-obsidian#36]
Hi. 

I want to insert just time without date.
How do this?

Thanks to make very nice plugin :)

**Comment by pbhopeful** [comment]
Is there a way for me to modify the javascript or create a custom plugin to add a natural language time insert, e.g. "@time" or "@moment" (I think "@now" would be best but that's already taken. 

This is maybe simple as another plugin, but I know very little javascript. Thank you so much for the wonderful plugin!

**Comment by argenos** [comment]
@pbhopeful Not yet possible with the inline suggestions. Will be fixed once I have some time to review and merge https://github.com/argenos/nldates-obsidian/pull/44

**Comment by levifig** [comment]
Why is `@now` already taken? It seems to do nothing in the current state of the plugin… 🤔 
Having @now introduce the time in the format we decide in the preferences (i.e. HH:mm) would be stellar IMO.

**Comment by argenos** [comment]
@levifig It's not released yet. Waiting on #57 before releasing.
