### ISSUE TITLE
Trigger phrase triggers inside code blocks and email addresses

### ISSUE THREAD

**Issue by OliverBalfour** [argenos/nldates-obsidian#38]
If I'm writing Python code inside \` \` \`py blocks with lots of decorators like `@property`, NL dates pops up all the time.

If it's an easy fix could the trigger phrase only trigger outside of code block contexts?

The same applies when writing email addresses - perhaps the @ should only trigger after whitespace and the popup should disappear if the phrase isn't part of a valid date string?

This is not a big deal as in the meantime I can just change the trigger phrase

**Comment by argenos** [comment]
Yeah, I use a different trigger since `@` is used by something else in my notes. I'll ping @liamcain in case he can do some magic on this/
