### ISSUE TITLE
What is the codebase license?

### ISSUE THREAD

**Issue by oeN** [argenos/nldates-obsidian#39]
Hi,

I'm working on an obsidian plugin and I'd like to reuse some code from this repo, in particular the files responsible for the autocomplete menu (https://github.com/argenos/nldates-obsidian/tree/master/src/suggest). The repo does not contain a license for the codebase, is it possible to add one? Can the code be re-used?

Thank you!

**Comment by argenos** [comment]
@liamcain was kind enough to contribute with the autosuggest feature, maybe he's got a suggestion for easily reusing this.

I'll add a LICENSE.md file as soon as I have some time, but you can in the meantime use the package.json info: 
https://github.com/argenos/nldates-obsidian/blob/5ebfadcdaecc421162cb0980e6b60a48693bfd81/package.json#L13

**Comment by oeN** [comment]
I've already figured it out 😄 just needed the peace of mind that I can use the code 😜

**Comment by liamcain** [comment]
There's a license file now. Closing this!
