### ISSUE TITLE
Potential time zone issue

### ISSUE THREAD

**Issue by deathau** [argenos/nldates-obsidian#4]
Greetings from the future!

I, on the morning of Monday 2020-11-02, at 10:45am (+11 UTC), typed "in two weeks" and used the plugin to convert it to a date, which output `[[2020-11-15]]`.  
However, two weeks from the 2nd *should* be the 16th.

Because I've seen this kind of problem before, my assumption is that the plugin is assuming UTC timezone without doing any conversion — 2020-11-02T10:45:00+1100 translates to 2020-11-01T23:45:00Z, and two weeks from that _would_ be the 15th, but I would appreciate if it could put that back in my local timezone for me, too.

**Comment by dariuszkowalski-com** [comment]
I have got a similar issue.  There was `2020-11-02` and time was `00:08`. When I tried to convert `next day` I have got `2020-11-02` -> I was expected `2020-11-03`. Today morning ~`08:00` local time it works as expected.

**Comment by argenos** [comment]
ahh good point! Let me see what I can do!

**Comment by argenos** [comment]
Could you check if 0.2.4 fixes this issue?

**Comment by deathau** [comment]
From my testing this morning, it all seems to be working fine!
Thanks!
