### ISSUE TITLE
Markdown links not created

### ISSUE THREAD

**Issue by menagerie198** [argenos/nldates-obsidian#48]
When parsing a dayname I am getting markdown links - `[Friday](2021-07-09)` rather than wikilinks. I have Add dates as links in NLD. Obs v0.12.9, NLD v0.5.2

**Comment by huyz** [comment]
Weird, I get Wikilinks.  But I have the opposite problem.  I don't want Wikilinks.  I've configured Obsidian to use Markdown links and NLD outputs Wikilinks.

**Comment by nikbrunner** [comment]
I have the same Problem as @menagerie198. I want WikiLinks but I get nromal Links
