### ISSUE TITLE
Enhancement suggestion: Key combination to paste date as plain text (i.e., not a link)

### ISSUE THREAD

**Issue by swehba** [argenos/nldates-obsidian#51]
To use an example, if you type the following:

`@today`

...and then hit `Enter`, nldates will paste in the current date **as a link**. If would be nice to be able to optionally interpret the date and paste it in without making it a link. `Shift-Enter` is already used. Perhaps `Ctrl-Enter` or` Opt-Enter`.

**Comment by compwiz32** [comment]
I would love this as well. I just want to add dates via natural language... I don't want to create a daily note...
