### ISSUE TITLE
Support for mobile?

### ISSUE THREAD

**Issue by PJJPtx** [argenos/nldates-obsidian#52]
I cannot get the plugin to work on mobile. Am I doing something wrong, or is this feature not supported? If not supported, are there plans to support mobile in the future?

Thanks for a great plugin!

**Comment by argenos** [comment]
I don’t consider it compatible yet. I think parts of it do work, which is why I haven’t made it desktop only.
I haven’t had time to do the migration to CM6 which is what mobile is using, so there are parts that won’t work. For now I believe you can use the modals only.

**Comment by jd-santos** [comment]
Ah, well at least I have confirmation that I’m not going crazy. +1 for needing this if it nudges the priority at all. Thanks!

**Comment by argenos** [comment]
@jd-santos Unfortunately, it doesn't. Happy to accept a PR if you're up to it!

**Comment by jd-santos** [comment]
This is not a temptation I needed but maybe 😂
