### ISSUE TITLE
Trigger (@ - or anything else) does not work in v0.13.2

### ISSUE THREAD

**Issue by lyonsquark** [argenos/nldates-obsidian#60]
The trigger text doesn't bring up the hint selector and does not translate text into date. It seems that the trigger is being ignored. 

I suspect the beta version of Obsidian has made a change that broke the trigger.

**Comment by liamcain** [comment]
This plugin is not yet compatible with the new Live Preview feature in Obsidian (0.13.0+). It will be fixed once #57 is merged.

**Comment by lyonsquark** [comment]
Sounds good! Thanks!
