### ISSUE TITLE
Bug: "week starts on" setting not respected, week always starts on Sunday

### ISSUE THREAD

**Issue by approximate** [argenos/nldates-obsidian#64]
I have the "Week starts on" setting set to "Monday" (not locale default!), and I am getting the following resolution:
```markdown
[[2021-11-20|this Saturday]]
[[2021-11-14|this Sunday]]
[[2021-11-27|next Saturday]]
[[2021-11-21|next Sunday]]
[[2021-11-13|last Saturday]]
[[2021-11-07|last Sunday]]
```

This looks like a bug, but maybe I am missing something? Also, do other Obsidian or system settings affect this resolution in any way? I changed the system settings to start the week on Monday, but this didn't affect the resolution.

**Comment by liamcain** [comment]
Hi @approximate, what version of the plugin are you using? 

There's an upcoming fix in v0.6.0 of the plugin (currently only compatible with the latest beta version of Obsidian) that should address this. I will update this ticket once that version because available to the public.

**Comment by approximate** [comment]
Hi @liamcain , I am using version 0.6.0.

![image](https://user-images.githubusercontent.com/1837916/143067853-5d87a7ef-2e5a-4c64-a6fc-a590bbd118c1.png)

Also, I am on Insiders version of the Obsidian, at the moment it's 0.13.5. I have just reproduced the bug after the restart.

**Comment by b1uegh0st** [comment]
I want to second this, everything updated to the latest (Insider version for Obs)

It seems mostly on the `@this week` for me, always come to a Sunday (and hence, of the previous week)
<img width="254" alt="image" src="https://user-images.githubusercontent.com/6695697/145810823-8881a126-b573-4835-b576-8d7985451e9e.png">

**Comment by liamcain** [comment]
Can reproduce the issue on 0.6.0. I'll make a fix soon. Sorry for the slow replies!
