### ISSUE TITLE
Mirror Daily Notes plugin for date format and folder

### ISSUE THREAD

**Issue by nickwarters** [argenos/nldates-obsidian#7]
If the Daily Notes plugin has enabled settings for date format and folders, the generated date format should be able to use these. 
A check box to "Mirror Daily Notes Plugin" and the standard option now would be fine. 

If the folder used in Daily Notes plugin is "Daily", the generated date should be [[Daily/generated_date_here]]

**Comment by argenos** [comment]
Hi @nickwarters, you can copy your daily note format into the Natural language date settings

![image](https://user-images.githubusercontent.com/5426039/98921723-e98c8f80-24d1-11eb-9fa4-0cd09d978cd7.png)

The plugin doesn't really control where notes are created, and only takes care of parsing dates. There is a feature request in the forum for that.
