### ISSUE TITLE
FR: Support `15th` format

### ISSUE THREAD

**Issue by SkepticMystic** [argenos/nldates-obsidian#73]
Hey :)

It'd be awesome if I could type `@@15th` and have it resolve as `2021-12-15`.
Ambiguity arises if the date given has already passed. For `@@2nd`, should it be the 2nd of December (already passed), or 2nd Jan (still to come). Perhaps this could be a setting? I personally would always want it to find the `2nd` still to come

**Comment by argenos** [comment]
I think this should work if you do "mid December"

**Comment by argenos** [comment]
For the 2nd case, someone recently asked about this in https://github.com/argenos/nldates-obsidian/discussions/70, but I can't understand the use case clearly, and it seems to me it would open a lot of edge cases, i.e. which reference date to use as a "start" when we try to parse dates. Can you or @Gnopps maybe mention in which contexts the dates should always refer to the future?

**Comment by Gnopps** [comment]
In my case I more often reference future dates than past dates, for example:
- Setting a deadline for a todo
- Planning for a future meeting
- Planning future project steps

**Comment by argenos** [comment]
Sorry, this is still vague enough that "often" means you still reference something in the present (this Tuesday vs next Tuesday) or the past (last Tuesday). If I set the reference to the "future", to get a date for this Tuesday you'd have to parse "last Tuesday", and the Tuesday from last week would have to be referenced by date e.g. Nov 30th. Does that make sense to you?

**Comment by Gnopps** [comment]
I understand you. I pretty rarely reference back dates, almost always future dates. So I'd prefer any generic "tue" will be interpreted as "next tue". Your suggestion looks good.

The chrono-lirbary supports this setting with "forwardDate", so couldn't that be a plugin setting if that should be enabled or not?

**Comment by argenos** [comment]
The point is that this is the way you use it, but other people don't. Making this a setting still introduces a lot of edge cases (like the ones above, even if you might not run into them). 

You can use how we use forwardDate here: https://github.com/argenos/nldates-obsidian/blob/master/src/parser.ts#L67

**Comment by liamcain** [comment]
fwiw, I actually found myself trying to use @2nd recently and was a bit disappointed to see `[[invalid date]]`. Since moment JS can parse date ordinals (1st, 2nd, 3rd), I think this should be easy to add.
