### ISSUE TITLE
Trigger phrase doesn't work with live preview

### ISSUE THREAD

**Issue by lizard-heart** [argenos/nldates-obsidian#78]
With the new obsidian editor update, I noticed that when I press my trigger phrase (in my case it's "@") nothing pops up. Switching to the legacy editor in Obsidian's preferences fixed the issue. Is there any way to use this trigger phrase functionality with live preview or does the plug-in need to be updated?

**Comment by liamcain** [comment]
Hi @lizard-heart, can you make sure you're on v0.6.0 of the plugin?

**Comment by lizard-heart** [comment]
Oh, that fixed it! Sorry for the issue!
