### ISSUE TITLE
Include a configuration option to keep the original text as an alias

### ISSUE THREAD

**Issue by Bejasc** [argenos/nldates-obsidian#8]
Mostly explained by the title.

Would work for some workflows, and be not so great for others. 

I use the dates almost exclusively in my Daily Notes - where I will often refer to "next week", "tomorrow", "on Wednesday", etc.  My date format is quite large `YYYY-MM-DD (ddd Do MMM)`, and in a "daily" context, not as easy to mentally parse/process as "tomorrow" in the context of a daily note.

In the case of using the plugin to resolve "next monday", I can do this manually by modifying the markdown to read as `[[2020-11-23 (Mon 23rd Nov)|next monday]]`, for it to read in preview mode as simply `next monday`

It would be great to include a config option to keep the original text as an alias (or even as a separate command in the command palette)

**Comment by pyjamads** [comment]
I did this locally, I'll make a pull request for it but it basically changes  "[[date]]" to  "[tag](date)" so the selected text becomes a link to that date instead...

**Comment by argenos** [comment]
@Bejasc v0.3.2 includes the changes in #16 in case you want to give it a try!

**Comment by liamcain** [comment]
I think this can be closed now, right @argenos?

**Comment by yasandev** [comment]
Is there a way to use this feature on mobile? I can only use it on the desktop.
