### ISSUE TITLE
Friday and next Friday in Monday doesn't work

### ISSUE THREAD

**Issue by dariuszkowalski-com** [argenos/nldates-obsidian#81]
Example 1:
- I am in monday - 2022-01-10
- Monday is set as a first day of week
- I enter  `friday`, select it and run 
![image](https://user-images.githubusercontent.com/37656900/148765819-09670280-752c-419d-965b-024732615fa5.png)
- text is translated tu [[2022-01-07]]
     - expected: [[2022-01-14]]

Example 2:
- I am in monday - 2022-01-10
- Monday is set as a first day of week
- I enter  `next friday`, select it and run 
![image](https://user-images.githubusercontent.com/37656900/148765819-09670280-752c-419d-965b-024732615fa5.png)
- text is translated tu [[2022-01-21]]
     - expected: [[2022-01-14]]

Is it a bug?

**Comment by ScottKillen** [comment]
I experienced something similar:

- Sunday is set as the first day of the week.
- Today is Tuesday 2022-01-18.
- `@thursday` renders 2022-01-13. I expect 2022-01-20.
- `@next Thursday` renders 2022-01-27.
- `@last Thursday` renders 2022-01-13.
- `@this Thursday` renders 2022-01-20.

I expect that `@Thursday` and `@this Thursday` would be synonymous. This is certainly how it works in natural language.

**Comment by Gnopps** [comment]
> I experienced something similar:
> 
>     * Sunday is set as the first day of the week.
> 
>     * Today is Tuesday 2022-01-18.
> 
>     * `@thursday` renders 2022-01-13. I expect 2022-01-20.
> 
>     * `@next Thursday` renders 2022-01-27.
> 
>     * `@last Thursday` renders 2022-01-13.
> 
>     * `@this Thursday` renders 2022-01-20.
> 
> 
> I expect that `@Thursday` and `@this Thursday` would be synonymous. This is certainly how it works in natural language.

This is similar to what I asked for here: https://github.com/argenos/nldates-obsidian/discussions/70. Basically that "Thursday" renders _next Thursday_ and not _last Thursday_.

The underlying engine "chrono" supports this [with a setting](https://github.com/wanasit/chrono#parsing-options), so ought to be fairly easy to implement.

**Comment by ScottKillen** [comment]
> This is similar to [what I asked for here](https://github.com/argenos/nldates-obsidian/discussions/70). Basically that "Thursday" renders _next Thursday_ and not _last Thursday_.
> 

Yes, that setting would certainly fix it.

**Comment by ScottKillen** [comment]
@Gnopps 

He manipulates the flag [here](https://github.com/argenos/nldates-obsidian/blob/master/src/parser.ts#L40), but I think there is a problem with the logic.
