### ISSUE TITLE
Let us add the calendar emoji infront of dates to make this plugin compatible with Tasks Plugin

### ISSUE THREAD

**Issue by kngautham** [argenos/nldates-obsidian#82]
Let us add the calendar emoji infront of dates to make this plugin compatible with Tasks Plugin. I use tasks Plugin and they have a very specific way to enter reminder dates. Right now adding dates through your plugin does not show in Tasks Plugin

**Comment by argenos** [comment]
Have you tried to add the emoji in the date format of the settings?

**Comment by 702573n** [comment]
It is possible to add any kind of emoji inside the date format field now. I'm also using both of this amazing plugins. So I have another feature request in combination with task plugin: I would like to create multiple custom date formats to quickly add different task dates (start, due, scheduled). A solution for this could be to add different triggers for different date formats. But any other solution is also welcome.

**Comment by argenos** [comment]
Hi @702573n, this sounds a bit out of scope for nldates. Have you tried asking the tasks plugin dev to provide such a format? nldates does provide a way for devs to use the parser.
