### ISSUE TITLE
Natural language in the date format parser

### ISSUE THREAD

**Issue by aisle9** [argenos/nldates-obsidian#87]
How can I do something like this without the parser rendering the first part of the tag?
I've tried a couple of special characters, but none of them seem to work.

Example: #date/YYYY-MM-DD

**Comment by liamcain** [comment]
Hi, could you provide some more information about what you're trying to do? It sounds like you just want `#date/` to be visually hidden, is that right?

**Comment by aisle9** [comment]
> Hi, could you provide some more information about what you're trying to do? It sounds like you just want `#date/` to be visually hidden, is that right?

No, what I want is for the first part "#date/" to always be rendered like that and not to be interpreted by the parser.

What I currently get: #5amt5/2022-03-04
What I want: #date/2022-03-04

**Comment by liamcain** [comment]
Oh, you can just surround that part of the format with brackets:


```
[#date]/YYYY-MM-DD
```
