### ISSUE TITLE
@ command not working anymore

### ISSUE THREAD

**Issue by himat** [argenos/nldates-obsidian#88]
For some reason, the Trigger Phrase for auto opening the date selector is no longer working

Before I could type `@` and choose 'Today' for example, but now when I type `@`, no window pops up

Here's my settings page.
![image](https://user-images.githubusercontent.com/1156974/156659294-1fe69fed-1b46-4975-8b45-e8e0725caf0d.png)

**Comment by vanakema** [comment]
If you've added an autocomplete plugin, turning it off might make it work. I made an issue as well #89

**Comment by argenos** [comment]
I'll close this in favour of #89. If it's unrelated to the completer plugin, I can reopen this
