### ISSUE TITLE
Adding query text as link text to resulting wikilink

### ISSUE THREAD

**Issue by linduxed** [argenos/nldates-obsidian#92]
Currently doing `@1 day ago<Enter>` (or whatever other valid query) results in something like `[[2022-03-07]]`, assuming wikilink insertion is on.

I'm wondering if it would be possible to have the query be inserted as link text, meaning that `@1 day ago<Enter>` would result in `[[2022-03-07|1 day ago]]`?

**Comment by linduxed** [comment]
Unless I'm misunderstanding, maybe this issue is related to this one: https://github.com/argenos/nldates-obsidian/issues/47

**Comment by liamcain** [comment]
This is already possible if you hold <kbd>Shift</kbd> when selecting the item from the autosuggest (so `shift+enter` will give you `[[2022-03-07|1 day ago]]`

**Comment by linduxed** [comment]
Ah, indeed! Thank you for informing me!

Closing.
